#!/usr/bin/env python3

import subprocess
import re
import argparse
import sys


def execute_capture_stderrout(cmd):
    popen = subprocess.Popen(cmd, stderr=subprocess.STDOUT, stdout=subprocess.PIPE,universal_newlines=True)
    for stdout_line in iter(popen.stdout.readline, ""):
         yield stdout_line
    popen.stdout.close()
    return_code = popen.wait()
    if return_code:
        raise subprocess.CalledProcessError(return_code, cmd)


parser = argparse.ArgumentParser(description='Launches JupyterLab in an interactive compute canada job, creating the required ssh tunnel.')

parser.add_argument('-u','--user',help='Remote server username',required=True)
parser.add_argument('--host',help='Remote server hostname (default: %(default)s)', default='graham.sharcnet.ca')
parser.add_argument('--time',help='Interactive job time (default: %(default)s)', default='3:00:00')
parser.add_argument('--ncpus',help='Interactive job ncpus (default: %(default)s)', default='4')
parser.add_argument('--mem',help='Interactive job memory (default: %(default)s)', default='8gb')
parser.add_argument('--account',help='Interactive job account (default: %(default)s)', default='ctb-akhanf')
parser.add_argument('--use_login_node',help='Use the login node directly, instead of submitting interactive job. You cannot use this for long jobs or those requiring more resources)  (default: %(default)s)', default=False, action='store_true')
parser.add_argument('--port',help='Local port to use for jupyter (default: %(default)s)', default='8888')
parser.add_argument('--venv',help='Path to remote virtualenv (default: %(default)s)', default='~/venv_jupyterlab')
parser.add_argument('--create_remote_venv',help='Create the remote virtualenv and pip install jupyterlab on it (default: %(default)s)', default=False, action='store_true')
parser.add_argument('--pip_install',help='Install packages to existing virtualenv using pip')
parser.add_argument('--verbose',help='Display verbose output (default: %(default)s)', default=False, action='store_true')



args = parser.parse_args()

if args.use_login_node == True:
    print('The login node feature is not fully operational yet -- exiting..')
    sys.exit(1)

#-- setup ssh command
ssh_cmd = ['ssh',f'{args.user}@{args.host}']
if args.verbose == True:
        ssh_cmd.extend(['-v','-v','-v'])

#-- check if virtualenv exists, will create if it does not exist
check_venv =  ssh_cmd + [f'[[ -f {args.venv}/bin/activate  ]]']
if subprocess.run(check_venv).returncode != 0:
    print('Virtualenv does not yet exist, will create it')
    args.create_remote_venv = True


#-- create virtualenv
if (args.create_remote_venv == True):
    #try creating the virtualenv remotely
    print(f'Creating remote virtualenv...')
    gen_remote_venv = ssh_cmd + [f'module load python/3 && virtualenv {args.venv} && source {args.venv}/bin/activate && pip install --upgrade pip && pip install jupyterlab']
    print(' '.join(gen_remote_venv))
    subprocess.run(gen_remote_venv)
    print('')


#-- pip install into virtualenv
if (args.pip_install != None):
    print(f'Installing pip packages to remote virtualenv...')
    pip_install_cmd = ssh_cmd + [f'source {args.venv}/bin/activate && pip install {args.pip_install}']
    print(' '.join(pip_install_cmd))
    subprocess.run(pip_install_cmd)
    print('')


#-- remote script for launching jupyter
remote_script = f'/home/{args.user}/.remote_jupyter_script'

remote_script_contents = '#!/bin/bash\n'\
             'unset XDG_RUNTIME_DIR\n'\
             f'{args.venv}/bin/jupyter lab --ip $(hostname -f) --no-browser\n'

print(f'Creating remote script to launch jupyter lab in {remote_script}...')
print(remote_script_contents)
gen_remote_script = ssh_cmd + ['-T',f'cat > {remote_script} && chmod a+x {remote_script}'] 
subprocess.run(gen_remote_script,encoding='ascii',input=remote_script_contents)
print('')


#set-up regex for capturing host & token
host_token_regex = 'http:\/\/(?!127)([-\w\d.]+):([0-9]+)\/(?:lab)\?token=([\w\d]+)'
host_token_pattern = re.compile(host_token_regex)
salloc_regex = 'salloc'
salloc_pattern = re.compile(salloc_regex)
jobnum_regex = 'salloc: Granted job allocation ([\d]+)'
jobnum_pattern = re.compile(jobnum_regex)


if args.use_login_node == True:
    jupyter_cmd = ssh_cmd + [f'{remote_script}']
    print('Launching jupyterlab on login node...')
else:
    jupyter_cmd = ssh_cmd + ['salloc',f'--time={args.time}',f'--cpus-per-task={args.ncpus}',f'--ntasks=1',f'--mem={args.mem}',f'--account={args.account}','srun',f'{remote_script}']

    print('Submitting jupyterlab interactive job...')

print(' '.join(jupyter_cmd))
print('')

for line in execute_capture_stderrout(jupyter_cmd):

    if args.verbose == True:
        print(line, end="")
    else:
        if (re.search(salloc_pattern,line) != None):
            print(line, end="")


    #check if job num in the line
    jobnum_match = re.search(jobnum_pattern,line)
    if jobnum_match != None:
        jobnum = jobnum_match.group(1)

    #check if the host/port/token from stderr is in the line
    host_token_match = re.search(host_token_pattern,line)
    print(host_token_match)
    if host_token_match != None:
        host,port,token = host_token_match.group(1,2,3)
        #debug, print match:
        #print(f'Matched pattern, host: {host}, port: {port}, token: {token}')
        break

print('')

#now, spawn the ssh process for tunnelling:
tunnel_cmd = ssh_cmd + ['-L', f'{args.port}:{host}:{port}','-N']

print('Starting ssh tunnel...  CTRL-C to kill tunnel')
print(' '.join(tunnel_cmd))
print('')

#run tunnel
p = subprocess.Popen(tunnel_cmd)


print('')
print('Open the following link in your web browser:')
print(f'http://localhost:{args.port}/?token={token}')
print('')


try:
    p.wait()
except KeyboardInterrupt:
    try:
        print('')
        if (args.use_login_node == False):
            print(f'Cancelling interactive job {jobnum}..')
            job_kill = ssh_cmd + [f'scancel {jobnum}']
            subprocess.run(job_kill)
        print('Killing ssh tunnel on 8888..')
        p.terminate()
    except OSError:
        pass
    p.wait()
